[project]
name = "prefect-methods"
version = "0.1.0"
description = "Prefect patterns and best practices"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prefect==3.4.19",
    "prefect-cloud==0.1.8",
]
