[project]
name = "prefect-methods"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "prefect",
    "prefect-cloud",
]

[project.scripts]
quickstart-01-demo = "01_getting_started:main"
